### ISSUE TITLE
Update servings description to servings rescued, donated, and financially supported

### ISSUE THREAD

**Issue by bharnav** [wwsalmon/stem4free#28]

**Comment by wwsalmon** [comment]
where? we can't really put this in the big number text

**Comment by wwsalmon** [comment]
![image](https://user-images.githubusercontent.com/25697428/92975587-9442ec00-f456-11ea-9330-7c13e284fa90.png)
![image](https://user-images.githubusercontent.com/25697428/92975983-7d50c980-f457-11ea-8660-17fa1582e24b.png)

changed it where I could
